# Generated by Django 3.2 on 2021-04-29 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_auto_20210428_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommember',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_member', to='tgbot.room'),
        ),
    ]
