# Generated by Django 3.2 on 2021-04-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_alter_roommember_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='about',
            new_name='description',
        ),
        migrations.AddField(
            model_name='room',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
