# Generated by Django 3.2 on 2021-05-02 12:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_auto_20210429_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='created',
            field=models.DateField(default=datetime.datetime(2021, 5, 2, 12, 8, 14, 609991)),
        ),
        migrations.AddField(
            model_name='roommember',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='tgbot.member'),
        ),
        migrations.AddField(
            model_name='roommember',
            name='wish',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='state',
            field=models.IntegerField(choices=[('0', 'Ожидание'), ('1', 'Ввод имени'), ('2', 'Ввод фамилии'), ('3', 'Ввод названия новой комнаты'), ('4', 'Ввод описания новой комнаты'), ('5', 'Ввод идентификатора комнаты'), ('6', 'Ввод пожеланий'), ('7', 'Ввод названия комнаты'), ('8', 'Ввод описания комнаты')], default=0),
        ),
    ]
