# Generated by Django 3.2 on 2021-05-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0006_alter_room_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='state',
            field=models.IntegerField(choices=[(0, 'Ожидание'), (1, 'Ввод имени'), (2, 'Ввод фамилии'), (3, 'Ввод названия новой комнаты'), (4, 'Ввод описания новой комнаты'), (5, 'Ввод идентификатора комнаты'), (6, 'Ввод пожеланий'), (7, 'Ввод названия комнаты'), (8, 'Ввод описания комнаты')], default=0),
        ),
    ]
