# Generated by Django 3.2 on 2021-05-02 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0007_alter_member_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Никнейм'),
        ),
        migrations.AlterField(
            model_name='roommember',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='tgbot.member'),
        ),
        migrations.AlterField(
            model_name='roommember',
            name='wish',
            field=models.TextField(blank=True, null=True),
        ),
    ]
